const translations = {
    es: {
        pageTitle: "Porfolio de Jonathan",
        navExperience: "Trayectoria",
        navProjects: "Proyectos",
        navAbout: "Sobre mí",
        navContact: "Contacto",
        heroTitle: "Hey! soy Jonathan Rodríguez",
        heroSubtitle: "Desarrollador Junior Full Stack",
        downloadCV: "Descargar CV",
        experienceWord: "Experiencia",
        laboralWord: "Laboral",
        job1: "Desarrollador en prácticas",
        job2: "Desarrollador full stack",
        dateJob1: "(Mayo 2024 - Junio 2024)",
        dateJob2: "(Enero 2025 - Actualidad)",
        educationHeading: "Estudios",
        edu1: "Bachillerato",
        edu2: "Desarrollo de Aplicaciones Multiplataforma",
        dateEdu1: "(2019 - 2021)",
        dateEdu2: "(2022 - 2024)",
        aboutHeading: "Sobre mí",
        aboutText1: "Graduado en Desarrollo de Aplicaciones Multiplataforma. A lo largo de mi formación, he adquirido sólidos conocimientos en la creación y adaptación de aplicaciones para diversas plataformas, como web, escritorio y móvil.",
        aboutText2: "He tenido la oportunidad de trabajar en equipo en diversos proyectos, colaborando de manera eficaz con mis compañeros para alcanzar los objetivos comunes. Además, me caracterizo por ser una persona trabajadora y responsable, siempre comprometido con entregar resultados de calidad en los plazos establecidos.",
        aboutText3: "Actualmente, me encuentro inmerso en proyectos personales, con el objetivo constante de mejorar mis habilidades y aportar valor a cada tarea que realizo.",
        contactHeading: "Contacta Conmigo",
        contactDesc1: "Reviso todos los correos electrónicos. Envíeme los mensajes que desee y le responderé con la mayor brevedad posible.",
        contactDesc2: "Necesito su Nombre y su Email, pero no recibirá nada más que mi respuesta.",
        contactFormTitle: "¡Mándame un mensaje!",
        labelName: "Nombre",
        labelEmail: "Email",
        labelSubject: "Asunto",
        labelMessage: "Mensaje",
        sendButton: "Enviar",
        rights: "Todos los derechos reservados."
    },
    en: {
        pageTitle: "Jonathan's Portfolio",
        navExperience: "Experience",
        navProjects: "Projects",
        navAbout: "About Me",
        navContact: "Contact",
        heroTitle: "Hey! I'm Jonathan Rodríguez",
        heroSubtitle: "Junior Full Stack Developer",
        downloadCV: "Download CV",
        experienceWord: "Work",
        laboralWord: "Experience",
        job1: "Intern Developer",
        job2: "Full Stack Developer",
        dateJob1: "(May 2024 - June 2024)",
        dateJob2: "(January 2025 – Present)",
        educationHeading: "Education",
        edu1: "High School",
        edu2: "Multiplatform Application Development",
        dateEdu1: "(2019 - 2021)",
        dateEdu2: "(2022 - 2024)",
        aboutHeading: "About Me",
        aboutText1: "Graduated in Multiplatform Application Development. Throughout my training, I acquired solid knowledge in creating and adapting applications for various platforms such as web, desktop, and mobile.",
        aboutText2: "I’ve had the opportunity to work in teams on various projects, collaborating effectively with colleagues to achieve common goals. I’m known for being hardworking and responsible, always committed to delivering quality results on time.",
        aboutText3: "Currently, I’m immersed in personal projects, constantly aiming to improve my skills and add value to every task I undertake.",
        contactHeading: "Get in Touch",
        contactDesc1: "I check all emails. Send me any message you want and I’ll reply as soon as possible.",
        contactDesc2: "I only need your Name and Email, and you won’t receive anything other than my response.",
        contactFormTitle: "Send me a message!",
        labelName: "Name",
        labelEmail: "Email",
        labelSubject: "Subject",
        labelMessage: "Message",
        sendButton: "Send",
        rights: "All rights reserved."
    }
};
